# To determine what is the largest prime factor of the number 600851475143 ?

factors = 0 # a place to put the factors which are the divors and quotients
#big_num = 600,851,475,143
big_num = 50 # chosen for known factors of 1, 2, 5, 10, 25, 50, of which 2 & 5 are primes factors the largest of which is 5
divisor = 2 # know factor generated by loop,  will use a second loop to divided by the big_ num and 1 but we want this to iterate first
quotient = 0 # the unknown factors

quotient = big_num / divisor
if divisor < big_num :
	divisor = divisor + 1

	if quotient > divisor :
		Q_factors = quotient

	else quotient < divisor:
			D_factors = divisor
else :
	break
print divisor		





